# Import all the models so that Base has them registered before migrating
from app.db.session import Base  # noqa
from app.models.user import User, UserRole  # noqa
from app.models.audit_log import AuditLog  # noqa
from app.models.agent import AgentRegistry  # noqa
from app.models.tool_model import Tool, Plugin, ToolExecutionLog  # noqa
from app.models.monitoring_model import SystemMetric, ExecutionMetric  # noqa
from app.models.document import Document  # noqa
from app.models.document_chunk import DocumentChunk  # noqa
from app.models.vector_embedding import VectorEmbedding  # noqa
from app.models.conversation import Conversation  # noqa
from app.models.message import Message  # noqa
from app.models.memory_entry import MemoryEntry  # noqa
from app.models.knowledge_collection import KnowledgeCollection  # noqa
from app.models.automation import AutomationJob, JobExecution, JobExecutionLog, Notification  # fmt: skip # noqa
from app.models.organization import Organization, Workspace, Team, TeamMember, Project, APIKey, ServiceAccount, Secret, SecretVersion, OrganizationInvitation, UsageRecord, EnterpriseAuditLog  # fmt: skip # noqa
from app.models.marketplace import MarketplaceCategory, MarketplacePublisher, MarketplaceItem, MarketplaceVersion, MarketplaceDependency, MarketplaceInstallation, MarketplacePurchase, MarketplaceReview, MarketplaceDownload, MarketplaceWishlist, MarketplaceLicense, MarketplaceRevenue, MarketplaceAnalytics, PluginPermission, PluginSignature, PluginSecret, PluginLog, PluginExecutionHistory, PluginCrashReport  # fmt: skip # noqa
from app.models.studio_models import AgentStudioProject, WorkflowCanvas, WorkflowNode, WorkflowEdge, PromptTemplate, PromptVersion, AgentTemplate, AgentVersion, Pipeline, PipelineVersion, Deployment, DeploymentHistory, ExecutionSession, DebugSession, CanvasLayout, WorkflowVariable, WorkflowParameter, WorkflowOutput, WorkflowTrigger, WorkflowSchedule, StudioWorkflowExecution, StudioWorkflowLog  # fmt: skip # noqa
from app.models.mcp_models import MCPServer, MCPClient, MCPConnection, ToolRegistry, ToolDefinition, ToolCategory, ToolPermission, ToolExecution, MCPToolExecutionLog, Connector, ConnectorCredential, ConnectorSecret, WebhookEndpoint, WebhookEvent, WebhookDelivery, RemoteEndpoint, RemoteSession, ToolVersion, ToolDependency, ToolUsageStatistics  # fmt: skip # noqa
from app.models.multimodal_models import VisionJob, ImageGenerationJob, ImageAnalysis, OCRDocument, DocumentExtraction, SpeechRecognitionJob, SpeechSynthesisJob, AudioAnalysisJob, VideoAnalysisJob, VideoFrame, MediaAsset, MediaFolder, MediaVersion, MediaMetadata, MediaEmbedding, MediaAnnotation, MediaTranscript, MediaTranslation, MediaSummary, MediaPipeline, MediaExecution, MediaProvider, MediaUsage  # fmt: skip # noqa
from app.models.model_management_models import ModelRegistry, ModelVersion, ModelArtifact, ModelDeployment, DeploymentHistory, Dataset, DatasetVersion, TrainingJob, FineTuningJob, EvaluationJob, Experiment, ExperimentRun, Checkpoint, HyperParameter, Benchmark, BenchmarkResult, PromptBenchmark, ModelRoute, ModelUsage, ModelCost, GPUWorker, TrainingQueue, EvaluationQueue, DeploymentQueue, InferenceEndpoint, ModelHealth, ModelMetrics, ModelApproval, ModelReview, ModelTag  # fmt: skip # noqa
from app.models.observability_models import ObsSystemMetric, ObsApplicationMetric, ObsTrace, ObsTraceSpan, ObsLogEntry, ObsAuditEvent, ObsAlertRule, ObsAlert, ObsIncident, ObsIncidentTimeline, ObsIncidentComment, ObsSecurityEvent, ObsThreatDetection, ObsCompliancePolicy, ObsComplianceReport, ObsRiskAssessment, ObsGovernancePolicy, ObsAIUsagePolicy, ObsModelAudit, ObsWorkflowAudit, ObsAgentAudit, ObsMCPAudit, ObsAPIAudit, ObsSystemHealth, ObsNodeHealth, ObsServiceHealth, ObsDashboard, ObsNotificationRule, ObsNotificationHistory  # fmt: skip # noqa
from app.models.infrastructure_models import InfraCluster, InfraNode, InfraDeployment, InfraPod, InfraNamespace, InfraServiceMesh, InfraIngress, InfraGateway, InfraLoadBalancer, InfraAutoScaler, InfraPersistentVolume, InfraStorageClass, InfraSecretManager, InfraConfigManager, InfraClusterPolicy, InfraEdgeNode, InfraEdgeDeployment, InfraDisasterRecoveryPlan, InfraBackupPolicy, InfraRestoreJob, InfraInfrastructureAudit  # fmt: skip # noqa
from app.models.devops_models import DevOpsRepository, DevOpsGitProvider, DevOpsBranch, DevOpsCommit, DevOpsPullRequest, DevOpsPipeline, DevOpsPipelineRun, DevOpsPipelineStage, DevOpsBuild, DevOpsArtifact, DevOpsArtifactVersion, DevOpsContainerImage, DevOpsContainerRegistry, DevOpsRelease, DevOpsReleaseNote, DevOpsDeployment, DevOpsDeploymentEnvironment, DevOpsApprovalRequest, DevOpsApprovalHistory, DevOpsRollback, DevOpsInfrastructureTemplate, DevOpsTerraformState, DevOpsGitOpsRepository, DevOpsSecretReference, DevOpsDeploymentPolicy, DevOpsChangeRequest  # fmt: skip # noqa
from app.models.data_platform_models import DPDataset, DPDatasetVersion, DPDatasetSchema, DPDatasetPartition, DPDatasetSnapshot, DPFeatureGroup, DPFeature, DPFeatureVersion, DPFeatureView, DPFeatureServingEndpoint, DPLakehouse, DPDataCatalog, DPMetadataEntry, DPDataLineage, DPDataSource, DPDataSink, DPETLPipeline, DPETLExecution, DPStreamingPipeline, DPStreamingTopic, DPStreamingConsumer, DPDataQualityRule, DPDataQualityReport, DPDataValidation, DPVectorDataset, DPEmbeddingIndex, DPMetadataTag, DPDataRetentionPolicy, DPDataAccessPolicy  # fmt: skip # noqa
from app.models.identity_models import IamIdentityProvider, IamFederatedIdentity, IamOrganizationIdentity, IamWorkspaceIdentity, IamUserSession, IamSessionHistory, IamSessionDevice, IamTrustedDevice, IamLoginHistory, IamAuthenticationAttempt, IamRefreshToken, IamAccessToken, IamOAuthClient, IamOAuthScope, IamOAuthConsent, IamAuthorizationPolicy, IamPolicyRule, IamPermissionAssignment, IamPermissionGroup, IamRoleHierarchy, IamServiceIdentity, IamMachineIdentity, IamAPIClient, IamAPISecret, IamPasskeyCredential, IamMFADevice, IamBackupCode, IamSecurityChallenge, IamRiskScore, IamAccessDecision, IamIdentityAudit  # fmt: skip # noqa

